import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Sidebar from "./components/layout/Sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Twitter Clone",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="xl:px-30 container mx-auto h-full max-w-6xl">
          <div className="grid h-full grid-cols-4">
            <Sidebar />
            <div
              className="
                col-span-3
                border-x-[1px]
                border-neutral-800
                lg:col-span-2
              "
            >
              {children}
            </div>
            <div className="text-sky-500">followbar</div>
            <div className="text-sky-500">section 4</div>
          </div>
        </div>
      </body>
    </html>
  );
}
